sudo: required
dist: trusty
language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

services:
  - postgresql
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
  firefox: "latest"

branches:
  only:
    - master

env:
  global:
    - CORE_BRANCH=stable10
    - NIGHTLY=false
  matrix:
    - DB=mysql

matrix:
  include:
    - php: 5.6
      env: "DB=sqlite"
    - php: 7.0
      env: "DB=sqlite"
    - php: 7.2
      env: "DB=sqlite"
    - php: 5.6
      env: "DB=pgsql"
    - php: 5.6
      env: "DB=mysql CORE_BRANCH=stable9.1"
    - php: 7.1
      env: "DB=sqlite CORE_BRANCH=master"
    - php: 7.1
      env: "DB=mysql CORE_BRANCH=master"
    - php: 7.1
      env: "DB=pgsql CORE_BRANCH=master"
    - php: 7.2
      env: "DB=sqlite CORE_BRANCH=master"
  fast_finish: true


before_install:
  # get a newer node.js version
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - nvm install 8
  - npm install -g npm@latest
  # install server
  - cd ../
  - git clone https://github.com/owncloud/core.git --recursive --depth 1 -b $CORE_BRANCH owncloud
  - mv calendar owncloud/apps/
  - cd owncloud
  - if [ "$CORE_BRANCH" != 'stable9' ] && [ "$CORE_BRANCH" != 'stable9.1' ]; then make; fi

cache:
  yarn: true
  directories:
  - owncloud/apps/calendar/js/node_modules
  - $HOME/.composer/cache/files

before_script:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  # Setup Postgres if applicable
  - if [[ "$DB" == 'pgsql' ]]; then psql -c 'create database oc_autotest;' -U postgres; fi
  - if [[ "$DB" == 'pgsql' ]]; then psql -c "create user oc_autotest with password '';" -U postgres; fi
  - if [[ "$DB" == 'pgsql' ]]; then psql -c 'grant all privileges on database oc_autotest to oc_autotest;' -U postgres; fi
  # Setup MySQL if applicable
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e 'create database oc_autotest;'; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "CREATE USER 'oc_autotest'@'localhost' IDENTIFIED BY '';"; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "grant all on oc_autotest.* to 'oc_autotest'@'localhost';"; fi
  # fill ownCloud with default configs and enable calendar
  - mkdir data
  - ./occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database $DB --database-pass=''
  - ./occ app:enable calendar
  - ./occ app:check-code calendar
  - php -S localhost:8080 &
  - cd apps/calendar

script:
  - make
  - make test
  - make dist

after_success:
  - cat ./coverage/*/lcov.info | ./js/node_modules/coveralls/bin/coveralls.js
  - bash <(curl -s https://codecov.io/bash)

after_failure:
    - cat ../../data/owncloud.log
