sudo: required
dist: trusty
language: php
php:
  - 5.6
  - 7

services:
  - postgresql
  
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
  firefox: "latest"
  
branches:
  only:
    - master

env:
  global:
    - CORE_BRANCH=stable9
    - NIGHTLY=false
  matrix:
    - DB=mysql

matrix:
  include:
    - php: 5.6
      env: "DB=sqlite"
    - php: 7
      env: "DB=sqlite"
    - php: 5.6
      env: "DB=pgsql"
    - php: 5.6
      env: "DB=pgsql"
  fast_finish: true


before_install:
  # get a newer node.js version
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - nvm install 6
  - npm install -g npm@latest
  # install core
  - cd ../
  - git clone https://github.com/owncloud/core.git --recursive --depth 1 -b $CORE_BRANCH owncloud
  - mv calendar owncloud/apps/
  - cd owncloud
  #- if [ "$CORE_BRANCH" != 'stable9' ] && [ "$CORE_BRANCH" != 'stable9.1' ]; then make; fi
  - cd apps/calendar/
  - make
  - cd ../../


before_script:
    - if [[ "$DB" == 'pgsql' ]]; then createuser -U travis -s oc_autotest; fi
    - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e 'create database oc_autotest;'; fi
    - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "CREATE USER 'oc_autotest'@'localhost' IDENTIFIED BY '';"; fi
    - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "grant all on oc_autotest.* to 'oc_autotest'@'localhost';"; fi
    # fill owncloud with default configs and enable news
    - mkdir data
    - ./occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database $DB --database-pass=''
    - ./occ app:enable calendar
    - ./occ app:check-code calendar
    - php -S localhost:8080 &
    - cd apps/calendar
    - cd js
    # install test deps
    - npm install --deps # npm install needs to run before sudo npm install because otherwise it fails because a tmp file exists in the home dir
    - npm -g install grunt-cli protractor
    - cd ..


script:
    - ../../../lib/composer/bin/phpunit --coverage-clover=coverage.clover tests/php
    - cd js/
    - grunt karma
    - grunt postcss
    - cd ..

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    - cat ./coverage/*/lcov.info | ./js/node_modules/coveralls/bin/coveralls.js

after_failure:
    - cat ../../data/owncloud.log

