<?php
/**
 * @author Thomas Citharel <tcit@tcit.fr>
 *
 * @copyright Copyright (c) 2016 Thomas Citharel <tcit@tcit.fr>
 * @license GNU AGPL version 3 or any later version
 *
 * This code is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License, version 3,
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */
namespace OCA\Calendar\Controller;

use OCP\AppFramework\Controller;
use OCP\AppFramework\Http;
use OCP\AppFramework\Http\JSONResponse;
use OCP\AppFramework\Http\TemplateResponse;
use OCP\Defaults;
use OCP\IConfig;
use OCP\IL10N;
use OCP\IRequest;
use OCP\IURLGenerator;
use OCP\IUserSession;
use OCP\Mail\IMailer;

class EmailController extends Controller {

	/**
	 * @var IConfig
	 */
	private $config;

	/**
	 * @var Defaults
	 */
	private $defaults;

	/**
	 * @var IL10N
	 */
	private $l10n;

	/**
	 * @var IMailer
	 */
	private $mailer;

	/**
	 * @var IUserSession
	 */
	private $userSession;

	/**
	 * @var IURLGenerator
	 */
	private $urlGenerator;

	/**
	 * @param string $appName
	 * @param IRequest $request an instance of the request
	 * @param IUserSession $userSession
	 * @param IConfig $config
	 * @param IMailer $mailer
	 * @param IL10N $l10N
	 * @param Defaults $defaults
	 * @param IURLGenerator $urlGenerator
	 */
	public function __construct(
		$appName,
		IRequest $request,
		IUserSession $userSession,
		IConfig $config,
		IMailer $mailer,
		IL10N $l10N,
		Defaults $defaults,
		IURLGenerator $urlGenerator
	) {
		parent::__construct($appName, $request);
		$this->config = $config;
		$this->userSession = $userSession;
		$this->mailer = $mailer;
		$this->l10n = $l10N;
		$this->defaults = $defaults;
		$this->urlGenerator = $urlGenerator;
	}

	/**
	 * @param string $to
	 * @param string $url
	 * @param string $name
	 * @return JSONResponse
	 * @NoAdminRequired
	 */
	public function sendEmailPublicLink($to, $url, $name) {
		$user = $this->userSession->getUser();
		if ($user === null) {
			return new JSONResponse([], Http::STATUS_UNAUTHORIZED);
		}
		$username = $user->getDisplayName();

		if (!$this->isValidPublicCalendarUrl($url)) {
			return new JSONResponse([], Http::STATUS_BAD_REQUEST);
		}

		$subject = $this->l10n->t('%s has published the calendar "%s"', [$username, $name]);

		$emailTemplateHTML = new TemplateResponse('calendar', 'mail.publication.html', ['subject' => $subject, 'username' => $username, 'calendarname' => $name, 'calendarurl' => $url, 'defaults' => $this->defaults], 'public');
		$bodyHTML = $emailTemplateHTML->render();
		$emailTemplateText = new TemplateResponse('calendar', 'mail.publication.text', ['subject' => $subject, 'username' => $username, 'calendarname' => $name, 'calendarurl' => $url], 'blank');
		$textBody = $emailTemplateText->render();

		$status = $this->sendEmail($to, $subject, $bodyHTML, $textBody);

		return new JSONResponse([], $status);
	}

	/**
	 * @param string $target
	 * @param string $subject
	 * @param string $body
	 * @param string $textBody
	 * @return int
	 */
	private function sendEmail($target, $subject, $body, $textBody) {
		if (!$this->mailer->validateMailAddress($target)) {
			return Http::STATUS_BAD_REQUEST;
		}

		$sendFromDomain = $this->config->getSystemValue('mail_domain', 'domain.org');
		$sendFromAddress = $this->config->getSystemValue('mail_from_address', 'owncloud');
		$sendFrom = $sendFromAddress . '@' . $sendFromDomain;

		$message = $this->mailer->createMessage();
		$message->setSubject($subject);
		$message->setFrom([$sendFrom => $this->defaults->getName()]);
		$message->setTo([$target => 'Recipient']);
		$message->setPlainBody($textBody);
		$message->setHtmlBody($body);
		$this->mailer->send($message);

		return Http::STATUS_OK;
	}

	/**
	 * Only links generated by this instance for a published calendar are
	 * allowed. This prevents the endpoint from being abused to send mails
	 * from the server identity that point recipients at attacker-controlled
	 * URLs (phishing).
	 *
	 * @param string $url
	 * @return bool
	 */
	private function isValidPublicCalendarUrl($url) {
		if (!\is_string($url) || $url === '') {
			return false;
		}

		// Must be an absolute http(s) URL.
		$scheme = \parse_url($url, PHP_URL_SCHEME);
		if (!\in_array($scheme, ['http', 'https'], true)) {
			return false;
		}

		// Base URL of the calendar app on this instance, e.g.
		// https://cloud.example.com/index.php/apps/calendar/ or, with a working
		// front controller, https://cloud.example.com/apps/calendar/.
		$appBase = $this->urlGenerator->linkToRouteAbsolute('calendar.view.index');
		if (\substr($appBase, -1) !== '/') {
			$appBase .= '/';
		}

		// The link must live below the calendar app base (same scheme, host and
		// port). The client always builds the public link with the "/index.php/"
		// front-controller segment (OC.linkTo), while linkToRouteAbsolute() omits
		// it when the front controller is active. Normalise that segment away on
		// both sides so a legitimate link is not rejected on pretty-URL instances.
		$normalize = static function ($value) {
			return \str_replace('/index.php/', '/', $value);
		};
		$normalizedBase = $normalize($appBase);
		$normalizedUrl = $normalize($url);
		if (\strpos($normalizedUrl, $normalizedBase) !== 0) {
			return false;
		}

		$path = \substr($normalizedUrl, \strlen($normalizedBase));

		// Reject any traversal segment so the path cannot be normalised by the
		// client into a different location under the same host.
		if (\preg_match('~(^|/)\.\.(/|$)~', $path)) {
			return false;
		}

		// The remainder must be one of the public sharing routes followed by a
		// non-empty token, mirroring appinfo/routes.php:
		//   p/{token}, p/{token}/{fancyName}, embed/{token}, public/{token}
		return (bool)\preg_match('~^(p|embed|public)/[^/?#]+~', $path);
	}
}
